### PR TITLE
Rewrite linux code to use libxdo

### LINKED ISSUE #38: Sending characer sequences is slow
First off let me say that I'm using linux.

I'd like to use this library to control the keyboard programmatically while the user is typing. I really like the API, but sending a character sequence takes a long time, at least 40ms per character due to sleeping 10ms before and after every keydown and keyup, so a single word can easily take half a second to print.

I tried forking and changing those sleep values but if it's too short, not all of the characters print, so I'm guessing they're there for good reason. 

I've been looking at plover, which is implemented in python. In plover, they also use XTest to send character sequences, but they render almost instantaneously. I can hammer keys as fast as I can and plover can easily keep up, turning single keystrokes into multi word sequences. 
See here https://github.com/openstenoproject/plover/blob/master/plover/oslayer/xkeyboardcontrol.py#L1223

They don't appear to be flushing after every keydown and keyup, but instead appear to be calling display.sync at the end of the key sequence. Is there any way enigo can print entire key sequences instantaneously or is there some limitation there?

### PR DESCRIPTION
**Pull request by jD91mZM2**
Hey! So I did this a while ago, but never thought it was worth making a fuzz about, until now when I wonder why the heck I didn't do it sooner.

**Note: This shouldn't be blindly merged. I'm putting this here for discussion.**

**Pros:**
- We let "the professionals" do the work. Any bugs are up to them to fix, and since xdotool has been a popular software for a while, you can assume it's probably going to work.
- It somehow fixes #38. Yay for that.
- A lot less code.

**Cons:**
- Doing "lower level" stuff like pressing a button based on keycode isn't yet implemented, and would generally be difficult or even impossible with a higher level library.
- We depend on libxdo, which isn't installed by default on most systems.

### CODE REVIEW

**Comment by jD91mZM2** [comment]
Idea: We could make this an optional feature!

**Comment by pythoneer** [comment]
I will merge this when i am back from my business trip. I guess i am just hesitating to kill the code that was so troublesome to write. But in the end what counts is that it works. If i have time we could make this feature based – as you suggested – but with the xdo more as a default (or anything that is working the best)

**Comment by jD91mZM2** [comment]
Poll: Feature based?

(React with :+1: and :-1:)

**Comment by pythoneer** [comment]
i am really for "feature based" in an ideal world but the problem i see is the increased complexity and the burden to maintain this because we need to check that both implementations behave the same etc. i am currently for just try how far we come with xdo

**Comment by pythoneer** [comment]
@jD91mZM2 the xdo branch is not typing the UNICODE chars e.g. the `keyboard.rs` example is typing the `❤️` on master but not on the `libxdo` branch – any ideas?

**Comment by jD91mZM2** [comment]
Hmm, I thought I tested that. Welp ok that's weird.

**Comment by jD91mZM2** [comment]
Ok it seems to be because of the `0` delay. Setting it to `12000` - the recommended amount - works. But is obviously slower.

**Pull request merged**
