### PR TITLE
Fix mouse_move_to for windows

### PR DESCRIPTION
**Pull request by Zeldern**
move_mouse_to didn't work properly on my system this pr fixes it.

Before: https://streamable.com/klfnx

After: https://streamable.com/9jjt8

### CODE REVIEW

**Comment by pythoneer** [comment]
Thanks for your PR! I have a question about the system you're running. Do you have two separate monitors or one big widescreen monitor? I am a little bit confused about what actually is happening. Unfortunately i currently have no access to a Windows setup with either multiple monitors or wide screen one. From the [documentation](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics) the parameters `78` and `79` should be the right ones. `0` and `1` are for the primary Monitor – that's why i am asking if you have a single wide screen monitor.

**Comment by Zeldern** [comment]
I have 2 monitors both 1080p 16:9 with the right one being marked as "primary". Basically using the co-ordinates from Enigo::mouse_location() in mouse_move_to() ended up in the wrong position the further away from 0 x/y you got.

In the clips i get the mouse location at the recycle bin and then click execute which uses mouse_move_to with that location.

**Comment by pythoneer** [comment]
That is interesting. Do you have any experience with this behavior? Because i am not quite sure if that is the right fix. What is happening if you primary monitor is on the left and your target is on the right monitor, thus all coordinates in the x direction should be positive the hole time. I am just wondering because we explicitly used the "virtual screen" which – as i understand it – should act like one big screen if you have two like in your setup. Getting the coordinates from "just" the primary monitor sound somehow wrong to me @jD91mZM2 what do you think?

**Comment by Zeldern** [comment]
With the left being primary the change still worked. I think the original code was wrong anyway with the 65335 as there is 0 to 65535 points

from reading the following https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmousemovepointsex#remarks we need to make use of SM_XVIRTUALSCREEN and SM_YVIRTUALSCREEN as in my case the left of the screen is negative values.

**Comment by Zeldern** [comment]
How about this

```
x * 65535 / unsafe { GetSystemMetrics(78) + GetSystemMetrics(76) },
y * 65535 / unsafe { GetSystemMetrics(79) + GetSystemMetrics(77) },```

if we assume that 76/77 are either 0 or negative because they're the top/left of the display then simply adding them to 78/79 which in my case would be something like 3840,2160 would give me the correct bounds. -1920 to 1920? and people that don't have displays on negative cords would simply see no change.

**Comment by Zeldern** [comment]
Ok, sorry for all the spam but I believe I found the solution.

MOUSEEVENTF_VIRTUALDESK as taken from https://docs.microsoft.com/en-gb/windows/win32/api/winuser/ns-winuser-mouseinput#remarks as well as converting the cords to 1:1 mapping with the virutal desktop by subtracting the top/left respectively.

```
fn mouse_move_to(&mut self, x: i32, y: i32) {
    mouse_event(
        MOUSEEVENTF_MOVE | MOUSEEVENTF_ABSOLUTE | MOUSEEVENTF_VIRTUALDESK,
        0,
        (x - unsafe { GetSystemMetrics(SM_XVIRTUALSCREEN) }) * 65535 / unsafe { GetSystemMetrics(SM_CXVIRTUALSCREEN) },
        (y - unsafe { GetSystemMetrics(SM_YVIRTUALSCREEN) }) * 65535 / unsafe { GetSystemMetrics(SM_CYVIRTUALSCREEN) },
    );
}
```

**Comment by Zeldern** [comment]
#90

**Pull request closed without merging**
