### PR TITLE
Serde

### LINKED ISSUE #31: Add Serde support
Implement Serde Serialize and Deserialize traits for Key and MouseButton as optional feature (like in the uuid crate).

### PR DESCRIPTION
**Pull request by legolord208**
This fixes #31.
No idea if I did it the optimal way. I'm very confused over how serde works.

Most changes are RustFmt... once again.

### CODE REVIEW

**Comment by Dampfnudeln** [comment]
Sorry, I didn't mention that you can propably just use serde_derive instead of writing all the implement code. But I can't say if it works out as I don't know the insides of enigo.

**Comment by Dampfnudeln** [comment]
I thought of something like this. But I can't test if it works.

```Rust
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum MouseButton {
    Left,
    Right,
    ...
}

#[cfg(feature = "serde")]
#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug)]
pub enum MouseButton {
    Left,
    Right,
    ...
}
```

**Comment by legolord208** [comment]
That probably does work. I feel like an idiot. Let me try that.

**Comment by legolord208** [comment]
Haven't actually tested it with a test, but it does at least compile

**Comment by Dampfnudeln** [comment]
Hmm, I have this in my Cargo.toml:
`enigo = { git = "https://github.com/enigo-rs/enigo", branch = "serde", features = ["with_serde"] }`
But I still get the error that Serialize, Deserialize and Clone are not implemented.

**Comment by legolord208** [comment]
Wait, Clone isn't implemented either?

**Comment by Dampfnudeln** [comment]
Actually it's Clone missing for Key and Debug missing for MouseButton.

**Comment by legolord208** [comment]
Yeah, Key doesn't have serde and stuff. I just wanna see if it works first. But yeah, debug isn't implemented for MouseButton. Should I add it?

**Comment by Dampfnudeln** [comment]
I think it would make sense to add Debug. Also I don't see any error about missing serde traits for MouseButton, so I it probably works.

**Pull request merged**
