### PR TITLE
Bump winapi to 0.3

### PR DESCRIPTION
**Pull request by Eijebong**
I also fixed the build on windows which was broken

### CODE REVIEW

**Comment by Eijebong** [comment]
Ping

**Comment by jD91mZM2** [comment]
Sadly I do not have a Rust setup on Windows myself, and therefore can't test this. @pythoneer can, but he's sadly a pretty busy person by the looks of it. Thank you for your patience.

**Comment by Eijebong** [comment]
Sure ;)

**Comment by pythoneer** [comment]
Sry, I am on production in a different city currently. I am back at home by the end of the week. Thanks for your patience :)

**Comment by jD91mZM2** [comment]
Haven't checked it, but it's a small change, appveyor succeeds, and I can't let this rot away.

**Pull request merged**
