### PR TITLE
Proper relative mouse move

### PR DESCRIPTION
**Pull request by CrendKing**
1. The relative mouse move function on Windows is implemented as getting absolute position + delta, while [`SendInput`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-mouseinput) itself supports relative move already. Why not use that to simplify the code?
2. According to the comment, the subsequent `SetCursorPos` seems to fix some issue, but to me it causes issue. For example, when pressing down left button while moving the mouse to select text, the `SetCursorPos` cancels the selection. Also causes compatibility issue with some apps like VSCode, where the cursor not longer stays as beam.

### CODE REVIEW

**Comment by pentamassiv** [comment]
I admit the code to control the mouse is a bit of a mess, but I don't know how to improve the situation. The Windows API has a few quirks that make it difficult to find an optimal solution. It would be nice to get help on improving the situation.

SendInput is subject to mouse acceleration and there is a difference between logical and physical pixels. Have you tested your code with different screens or scaling factors? When I change the scale of the display from 200% to 100%, the code no longer has the expected effect.

**Comment by CrendKing** [comment]
According to my test, SendInput does not subject to mouse acceleration, which I assume you referring to the "Enhance pointer precision" setting in Control Panel. Also, when I set display scale to 200%, I see the mouse move at 200% speed. I'm not sure if that the expected effect. In fact, exactly because SendInput doesn't have either mouse acceleration or key repeating effect, I have to implement them myself, which is a fun experience.

I'm on Windows 11 23H2 ver 22631.2861. I wonder if the problems you see was from earlier version.

**Comment by mbwilding** [comment]
This PR fixed some weird bugs with windows mouse movement. This works a lot better.

**Comment by pentamassiv** [comment]
Okay, since it seems to help you, I'll merge it. Thank you for the PR :-)

**Pull request merged**
